-- DDL for Placement Cell Management System (Oracle Version)

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Offers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RoundResults CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE InterviewRounds CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Applications CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE JobRoles CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Companies CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Students CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- Users Table (Added for Authentication)
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'student' CHECK (role IN ('admin', 'student', 'recruiter'))
);

-- Students Table
CREATE TABLE Students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id) ON DELETE CASCADE,
    name VARCHAR2(100) NOT NULL,
    cgpa NUMBER(4, 2) CHECK (cgpa >= 0 AND cgpa <= 10),
    branch VARCHAR2(50) NOT NULL,
    grad_year NUMBER(4) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    status VARCHAR2(20) DEFAULT 'Unplaced' CHECK (status IN ('Unplaced', 'Placed', 'Interned'))
);

-- Companies Table
CREATE TABLE Companies (
    company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    industry VARCHAR2(50),
    location VARCHAR2(100)
);

-- JobRoles Table
CREATE TABLE JobRoles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id NUMBER REFERENCES Companies(company_id) ON DELETE CASCADE,
    title VARCHAR2(500) NOT NULL,
    type_of_offer VARCHAR2(200), -- e.g., Intern, FTE, Intern+FTE
    package_ctc NUMBER, -- in LPA
    stipend NUMBER, -- per month
    eligibility_cgpa NUMBER(4, 2),
    branches_allowed VARCHAR2(1000), -- Comma separated branch codes
    last_date_to_apply DATE
);

-- Applications Table
CREATE TABLE Applications (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER REFERENCES Students(student_id) ON DELETE CASCADE,
    role_id NUMBER REFERENCES JobRoles(role_id) ON DELETE CASCADE,
    app_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Shortlisted', 'Rejected', 'Selected')),
    CONSTRAINT unique_app UNIQUE(student_id, role_id)
);

-- InterviewRounds Table
CREATE TABLE InterviewRounds (
    round_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER REFERENCES JobRoles(role_id) ON DELETE CASCADE,
    round_number NUMBER NOT NULL,
    round_type VARCHAR2(50) NOT NULL, -- e.g., OA, Technical, HR
    scheduled_date DATE
);

-- RoundResults Table
CREATE TABLE RoundResults (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER REFERENCES Applications(application_id) ON DELETE CASCADE,
    round_id NUMBER REFERENCES InterviewRounds(round_id) ON DELETE CASCADE,
    score NUMBER,
    result_status VARCHAR2(20) CHECK (result_status IN ('Selected', 'Rejected'))
);

-- Offers Table
CREATE TABLE Offers (
    offer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER REFERENCES Applications(application_id) ON DELETE CASCADE,
    offer_date DATE DEFAULT SYSDATE,
    package_offered NUMBER,
    acceptance_status VARCHAR2(20) DEFAULT 'Pending' CHECK (acceptance_status IN ('Pending', 'Accepted', 'Rejected'))
);

